name: linter
on:
  workflow_dispatch: {}
  pull_request:
    branches: [ master ]

jobs:
  linter:
    runs-on: ubuntu-latest
    container:
      image: python:3.9-bookworm
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s

    steps:
      - name: Checkout code repository in agent
        uses: actions/checkout@v4
        with:
          set-safe-directory: true

      # https://github.com/actions/runner/issues/2033#issuecomment-1204205989
      - name: Set ownership
        run: |
          # this is to fix GIT not liking owner of the checkout dir
          chown -R $(id -u):$(id -g) $PWD

      - name: Install postgres client tools
        run: |
          bash ./bin/install-postgres.sh

      - name: Restore Postgres CI database
        run: |
          bash ./bin/restore.sh
        env:
          PGHOST: postgres
          PGPORT: 5432
          # In practice, you would use a secrets module to manage secrets
          # See: https://docs.github.com/en/actions/security-guides/using-secrets-in-github-actions
          PGPASSWORD: postgres
          PGUSER: postgres
          PGDATABASE: adventureworks
          DBT_TARGET: ci

      - name: Set up python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ./transform/dbt/requirements.txt

      - name: Run linting checks. Exit code 1 if linter failed
        run: |
          bash ./bin/linter.sh
